version: '3'

services:

  nginx:  
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "8080:80"
    networks:
      - nodenet
    links:
      - app
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    restart: always
    networks:
      - nodenet
    # volumes:
    #   - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    command: [--innodb-use-native-aio=0]
    restart: always
    tty: true
    # volumes:
    #   - ./mysql:/home/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATA_DIR=/home/mysql
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge